#include "Globals.h"

// Define the centralized block color table here. Values are scaled by BRIGHTNESSDIV.
const uint8_t block_colors[NUM_BLOCKS][3] = {
    {0/BRIGHTNESSDIV, 255/BRIGHTNESSDIV, 80/BRIGHTNESSDIV},   // I - Cyan
    {0/BRIGHTNESSDIV, 0/BRIGHTNESSDIV, 255/BRIGHTNESSDIV},     // J - Blau
    {255/BRIGHTNESSDIV, 90/BRIGHTNESSDIV, 0/BRIGHTNESSDIV},   // L - Orange
    {255/BRIGHTNESSDIV, 240/BRIGHTNESSDIV, 0/BRIGHTNESSDIV},   // O - Gelb
    {0/BRIGHTNESSDIV, 255/BRIGHTNESSDIV, 0/BRIGHTNESSDIV},     // S - Grün
    {128/BRIGHTNESSDIV, 0/BRIGHTNESSDIV, 128/BRIGHTNESSDIV},   // T - Lila
    {255/BRIGHTNESSDIV, 0/BRIGHTNESSDIV, 0/BRIGHTNESSDIV}      // Z - Rot
};
